import Head from "next/head";
import styles from "../../styles/Home.module.css";
import dStyles from "../../styles/Devs.module.css";
import Link from "next/link";
export default function Dev({ devs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coder.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://instagram.com/_coder.dev" target="blank">
            Devs
          </a>
        </h1>
        <div className={dStyles.cardContainer}>
          {devs.map((dev) => {
            return (
              <Link key={dev.id} href={`/devs/${dev.id}`}>
              <a>
              <div className={dStyles.card} >
                <p className={dStyles.pText}>{dev.name}</p>
                <span className={dStyles.text}>{dev.email}</span>
              </div>
              </a>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();
  return {
    props: {
      devs: data,
    },
  };
};
